### ISSUE TITLE
the latest version dont support mysql 8.0 as storage

### ISSUE THREAD

**Issue by gouhan** [openzipkin/zipkin#3441]
I fount the latest docker image only can work with lower version mysql,eg 5.7.
but download the history version of 2.21.5,it can works with mysql 8.0 fine.
Mean while,I checked the docker hub image version with github's release version,is consistent too.
Is there any problem occurs when merging the pull request?

**Comment by jcchavezs** [comment]
Would you open a PR with the fix?

lør. 2. apr. 2022, 07:47 skrev luoqingsong ***@***.***>:

**Comment by gouhan** [comment]
ok,i should take time to review the history commits of changes.
I try it ,thanks very much.

**Comment by qzmer1104** [comment]
not fixed yet

**Comment by qianleijava** [comment]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.mariadb.jdbc.internal.com.send.authentication.SendGssApiAuthPacket




Brothers, is it the same error log?

**Comment by ajax-osadchuk-r** [comment]
@jcchavezs Could you please clarify whether Zipkin is going to support MySQL 8 in near future?

**Comment by beertje44** [comment]
Would be a nice enhanchment, running years old software makes me nervious ;)
And from the looks of it the bundled mysql for docker is mysql 3.x!!!!!!!!

Please fix this :)

**Comment by rmannibucau** [comment]
+1

**Comment by huahuo840** [comment]
I use zipkin version 2.24.3 and mysql version 8.0.21

I found that if I downloaded zipkin from docker and used mysql persistence, I would report version compatibility errors

But pushing the 2.24.3 jar package onto docker and using mysql persistence is fine

It's weird, I tested three servers with the same problem

**Comment by codefromthecrypt** [comment]
zipkin tests run against our docker image which is MySQL 10.11.7
